version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # https://github.com/dependabot/dependabot-core/issues/2178
  # k8s manifests
  # - package-ecosystem: "docker"
  #   directory: "/ansible/manifests/cloudflared"
  #   schedule:
  #     interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ansible/manifests/nextcloud"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "mariadb"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/ansible/manifests/hackmd"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "mariadb"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "docker"
    directory: "/ansible/manifests/growi"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "mongo"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
