apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud
  namespace: nextcloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-exec
  namespace: nextcloud
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud
  namespace: nextcloud
subjects:
  - kind: ServiceAccount
    name: nextcloud
    namespace: nextcloud
roleRef:
  kind: Role
  name: nextcloud-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cronjob
  namespace: nextcloud
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: nextcloud
          containers:
            - name: kubectl
              image: ghcr.io/isec-tut/containers/kubectl@sha256:451ee9f69cd0cdb9d79d5f5bb568ea4d1b8246e6e635128802b6dc7334cda3f9
              imagePullPolicy: IfNotPresent
              args:
                [
                  "exec",
                  "-n",
                  "nextcloud",
                  "nextcloud-0",
                  "-c",
                  "nextcloud",
                  "--",
                  "/bin/sh",
                  "-c",
                  'su www-data --shel=/bin/sh --command="/usr/local/bin/php -f /var/www/html/cron.php"',
                ]
          restartPolicy: Never
