apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-env
  namespace: nextcloud
data:
  TZ: "Asia/Tokyo"
  NEXTCLOUD_ADMIN_USER_FILE: /secrets/nextcloud_admin_user
  NEXTCLOUD_ADMIN_PASSWORD_FILE: /secrets/nextcloud_admin_password
  NEXTCLOUD_DATA_DIR: /mnt/nextcloud
  OVERWRITEPROTOCOL: https
  TRUSTED_PROXIES: nextcloud
  NEXTCLOUD_TRUSTED_DOMAINS: files.isec-lab.org
  MYSQL_HOST: nextcloud-mariadb
  MYSQL_USER: nextcloud
  MYSQL_DATABASE: nextcloud
  MYSQL_PASSWORD_FILE: /secrets/nextcloud_mariadb_user_password
  REDIS_HOST: nextcloud-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  serviceName: nextcloud
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: nextcloud
          image: ghcr.io/isec-tut/containers/nextcloud@sha256:e3d8f32e08bc836cc43f0e7df9e82709b63292b12b465088785c94f8dfd49d6d
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nextcloud-env
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: data
              mountPath: /mnt/nextcloud
            - name: nextcloud-secrets
              mountPath: /secrets
            - name: nextcloud-conf
              mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
              subPath: zz-docker.conf
              readOnly: true
            - name: nextcloud-conf
              mountPath: /usr/local/etc/php/conf.d/nextcloud.ini
              subPath: nextcloud.ini
              readOnly: true
            - name: nextcloud-hooks
              mountPath: /docker-entrypoint-hooks.d/before-starting/config.sh
              subPath: config.sh
              readOnly: true
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
        - name: nginx
          image: nginx:1.25.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: nginx-nextcloud
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/nextcloud.conf
              subPath: nextcloud.conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 2000Mi
      volumes:
        - name: nextcloud-secrets
          projected:
            sources:
              - secret:
                  name: nextcloud-secrets
              - secret:
                  name: fqdn-secrets
        - name: nextcloud-conf
          configMap:
            name: nextcloud-conf
        - name: nextcloud-hooks
          configMap:
            defaultMode: 504
            name: nextcloud-hooks
        - name: nginx-conf
          configMap:
            name: nginx-conf
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
    - metadata:
        name: app
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: iscsi-ssd-storage
        resources:
          requests:
            storage: 30Gi
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: iscsi-ssd-storage
        resources:
          requests:
            storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
    - name: nginx-nextcloud
      port: 80
      targetPort: nginx-nextcloud
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nextcloud
  namespace: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.isec-lab.org
      secretName: nextcloud-cert
  rules:
    - host: files.isec-lab.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  name: nginx-nextcloud
