apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-conf
  namespace: nextcloud
data:
  nextcloud.ini: |
    memory_limit=1024M

    upload_max_filesize=512M
    post_max_size=512M

    request_terminate_timeout=3600
    max_execution_time=3600
    output_buffering=0

  zz-docker.conf: |
    [global]
    daemonize = no
    log_limit = 8192
    error_log = /proc/self/fd/2

    [www]
    user  = www-data
    group = www-data

    listen = 0.0.0.0:9000

    access.log = /proc/self/fd/2
    access.format = "%{REMOTE_ADDR}e - %u %t \"%m %{REQUEST_URI}e\" %s"

    pm                   = dynamic
    pm.max_children      = 10
    pm.start_servers     = 2
    pm.min_spare_servers = 2
    pm.max_spare_servers = 7
    pm.max_requests      = 1500

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-hooks
  namespace: nextcloud
data:
  config.sh: |
    #!/bin/sh
    set -eu

    php /var/www/html/occ app:enable files_external
    php /var/www/html/occ app:enable twofactor_totp
    php /var/www/html/occ app:enable admin_audit
    php /var/www/html/occ app:enable oidc_login

    php /var/www/html/occ config:system:set oidc_login_provider_url --value="https://$(cat /secrets/auth_fqdn)/dex"
    php /var/www/html/occ config:system:set oidc_login_client_id --value="nextcloud"
    php /var/www/html/occ config:system:set oidc_login_client_secret --value="$(cat /secrets/nextcloud_client_secret)"
    php /var/www/html/occ config:system:set oidc_login_default_group --value="User"
    php /var/www/html/occ config:system:set oidc_login_attributes id --value="sub"
    php /var/www/html/occ config:system:set oidc_login_attributes name --value="name"
    php /var/www/html/occ config:system:set oidc_login_attributes mail --value="email"
    php /var/www/html/occ config:system:set oidc_login_disable_registration --type=boolean --value=false

    php /var/www/html/occ config:system:set default_phone_region --value=JP
    php /var/www/html/occ config:app:set files max_chunk_size --value 94371840 # 90MiB
