apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6.16
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: nextcloud
          image: ghcr.io/isec-tut/containers/nextcloud@sha256:853d2472cf144efafc30c5874f7e389bcc652b03d3beded418a711ffa3ce8d21
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
