apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6.20
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: nextcloud
          image: ghcr.io/isec-tut/containers/nextcloud@sha256:9431891fb0a92cfbdfe8afd3c902319804da526b3ad3930423e7f1afe8c74b22
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
