apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6.18
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: nextcloud
          image: ghcr.io/isec-tut/containers/nextcloud@sha256:55773d82de598c3ee4827cc240e5fea4e2f7532a71f4e3a834efda17daa3fe49
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
