apiVersion: v1
kind: Secret
metadata:
  name: vso-secrets
  namespace: hackmd
  annotations:
    replicator.v1.mittwald.de/replicate-from: vault-secrets-operator/vso-secrets
type: Opaque
data: {}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: hackmd-secrets
  namespace: hackmd
spec:
  appName: hackmd
  hcpAuthRef: vault-secrets-operator/hcp-auth
  destination:
    create: true
    name: hackmd-secrets
