apiVersion: v1
kind: Secret
metadata:
  name: vso-secrets
  namespace: growi
  annotations:
    replicator.v1.mittwald.de/replicate-from: vault-secrets-operator/vso-secrets
type: Opaque
data: {}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: growi-secrets
  namespace: growi
spec:
  appName: growi
  hcpAuthRef: vault-secrets-operator/hcp-auth
  destination:
    create: true
    name: growi-secrets
